### ISSUE TITLE
[Bug]: Selling heads using the GUI doesnt seem to work

### ISSUE THREAD

**Issue by FourNineRugz** [Errored-Innovations/HeadsPlus#92] opened 2022-01-06 09:35 UTC
### Checklist

- [X] Are you using the latest version/snapshot of [HeadsPlus](https://ci.pluginwiki.us/job/HeadsPlus/)?
- [X] Have you checked to see if others have submitted the same bug report?
- [X] Have you been able to reproduce the bug more then once?

### Description of the bug

![image](https://user-images.githubusercontent.com/17154368/148361647-0addd76e-c8f9-4dd4-b7fa-3f12ec398d4d.png)

Using the sellhead GUI, players are not able to sellheads. Even if the head is in their inventory. Assuming NBT tags arent matching up for some reason...

### Steps To Reproduce

Get mob head
Type /sellhead
Attempt to sellhead

I've refreshed my headsplus files, still doesn't seem to work.

**Comment by Thatsmusic99** [comment] 2022-01-06 11:45
Yeah, the sellhead command syntax switched up a while ago so it's no surprise this doesn't work. Let me sort that out.

**Comment by Thatsmusic99** [comment] 2022-01-06 14:01
Should be fixed in dev build 62: https://ci.pluginwiki.us/job/HeadsPlus/62/artifact/target/HeadsPlus-7.0.3+DEV_62.jar

**Closed** 2022-01-06 15:40 UTC
Labels: bug, v7

**Comment by cloakfox** [comment] 2022-04-05 12:36
Getting same issue on latest headsplus 7.0.5 & paper 1.17.2
also tried grabbing fresh files.

https://i.imgur.com/SHoRw6Y.png
https://i.imgur.com/F0aNb9K.png

**Comment by Thatsmusic99** [comment] 2022-04-05 12:42
This is likely due to the NBT tags either not being updated properly or not fixed, please re-open this issue using the issue template instead of hijacking a closed issue, and provide information about the head from `/data get entity Username SelectedItem` (or if that doesn't work, hold the head in your first slot and do `/data get entity Username Inventory[{Slot:0b}}`.

**Comment by cloakfox** [comment] 2022-04-05 12:59
> 

It should be fairly easy to reproduce on your end with fresh files, I dont believe this issue is fixed, dont see how creating a new bug report will help you. This thread works & is the exact same issue as im having currently, the OP of this thread also never replied.

im getting this output with that command ;(
![2022-04-05_14-54](https://user-images.githubusercontent.com/3696645/161758362-57a81c44-8d47-4b61-8c2f-068b27845e53.png)

**Comment by Thatsmusic99** [comment] 2022-04-05 13:09
![image](https://user-images.githubusercontent.com/25277367/161760078-8b8a0863-e170-4b45-8f20-c78b7ab9061f.png)
Didn't reproduce with fresh files. New issue reports ensure that all necessary information is provided, especially if I can't reproduce the issue again in a later version, and don't fill OP's notifications.

This sounds more like older heads that need fixing, which can be done by holding a head and doing `/hp debug fix <Head ID>`. If you don't have permission to the command, add it using `headsplus.maincommand.debug.fix`. You're free to poke me about this over Discord since I feel like this is a more localised issue rather than an issue that affects everyone.

With the command output, that would be my mistake, it's `/data get entity Username Inventory[{Slot:0b}]`.
